<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Item\Module'                        => __DIR__ . '/Module.php',
    'Item\Controller\ItemController' => __DIR__ . '/src/Item/Controller/ItemController.php',
    'ItemTest\Framework\TestCase'        => __DIR__ . '/tests/Item/Framework/TestCase.php',
    'ItemTest\SampleTest'                => __DIR__ . '/tests/Item/SampleTest.php',
);
